require "user.custom_commands.autorun"
require "user.custom_commands.autotex"
require "user.custom_commands.toggledarkplus"
require "user.custom_commands.organize_imports"
require "user.custom_commands.toggleInlayHints"
