require "user.autocommands.dependencies_manager"
require "user.autocommands.fugitive"
require "user.autocommands.general"
require "user.autocommands.lsp"
require "user.autocommands.obsidian"
require "user.autocommands.vertical_help"
require "user.autocommands.trouble"
