local colors = require "material.colors"

return {
  NavicIconsFile = { fg = colors.title },
  NavicIconsModule = { fg = colors.title },
  NavicIconsNamespace = { fg = colors.yellow },
  NavicIconsPackage = { fg = colors.title },
  NavicIconsClass = { fg = colors.yellow },
  NavicIconsMethod = { fg = colors.blue },
  NavicIconsProperty = { fg = colors.purple },
  NavicIconsField = { fg = colors.cyan },
  NavicIconsConstructor = { fg = colors.purple },
  NavicIconsEnum = { fg = colors.darkyellow },
  NavicIconsInterface = { fg = colors.yellow },
  NavicIconsFunction = { fg = colors.blue },
  NavicIconsVariable = { fg = colors.paleblue },
  NavicIconsConstant = { fg = colors.paleblue },
  NavicIconsString = { fg = colors.darkorange },
  NavicIconsNumber = { fg = colors.darkorange },
  NavicIconsBoolean = { fg = colors.green },
  NavicIconsArray = { fg = colors.orange },
  NavicIconsObject = { fg = colors.orange },
  NavicIconsKey = { fg = colors.cyan },
  NavicIconsNull = { fg = colors.red },
  NavicIconsEnumMember = { fg = colors.darkyellow },
  NavicIconsStruct = { fg = colors.yellow },
  NavicIconsEvent = { fg = colors.darkred },
  NavicIconsOperator = { fg = colors.red },
  NavicIconsTypeParameter = { fg = colors.darkgreen },
  NavicText = { fg = colors.fg },
  NavicSeparator = { fg = colors.fg },
  IndentBlanklineContextChar = { fg = colors.fg },
}
